
%For Baseline Simulations, Set all paramters to 1 and Percentage cells to 1
%Also change the number of simulations to 1000 in Beard_NC_simulatePopulation

%%%Change the outputs in Beard_NC_simulatePopulation to all outputs, search
%%%all outputs



Par_vary = ones(1,8);
percentage_cells = 1;

load("All_Par_with_ROS_2_Percent.mat")

%Simulate all the experiments, For e.g. 3: OCR, 1: Rot

 
    
       [OCR_Sea(:,:),  delPsi_basal, ATP_m_basal, NADH_m_basal, ATP_c_basal, H2O2_c_basal,...
        delPsi_Oligo, ATP_m_Oligo, NADH_m_Oligo, ATP_c_Oligo,...
        delPsi_Oligo_FCCP, ATP_m_Oligo_FCCP, NADH_m_Oligo_FCCP, ATP_c_Oligo_FCCP,...
        delPsi_FC_Oligo, delPsi_FC_Oligo_FCCP, ATP_m_FC_Oligo, ATP_m_FC_Oligo_FCCP,...
        NADH_m_FC_Oligo, NADH_m_FC_Oligo_FCCP...
        ] = Beard_NC_simulatePopulation(3, Par_vary, percentage_cells)
    
  
        
                            [Oxygen_1(:,:), delPsi_basal_1, ATP_m_basal_1, NADH_m_basal_1, ATP_c_basal_1,H2O2_c_basal_1,...
        delPsi_Rot, ATP_m_Rot, NADH_m_Rot, ATP_c_Rot,...
        delPsi_Rot_Oligo, ATP_m_Rot_Oligo, NADH_m_Rot_Oligo, ATP_c_Rot_Oligo,...
        delPsi_FC_Rot, delPsi_FC_Rot_Oligo, ATP_m_FC_Rot, ATP_m_FC_Rot_Oligo,...
        NADH_m_FC_Rot, NADH_m_FC_Rot_Oligo...
        ] = Beard_NC_simulatePopulation(1, Par_vary, percentage_cells)
    
                                [Oxygen_2(:,:), delPsi_basal_2, ATP_m_basal_2, NADH_m_basal_2, ATP_c_basal_2,H2O2_c_basal_2,...
        delPsi_AA, ATP_m_AA, NADH_m_AA, ATP_c_AA,...
        delPsi_AA_Oligo, ATP_m_AA_Oligo, NADH_m_AA_Oligo, ATP_c_AA_Oligo,...
        delPsi_FC_AA, delPsi_FC_AA_Oligo, ATP_m_FC_AA, ATP_m_FC_AA_Oligo,...
        NADH_m_FC_AA, NADH_m_FC_AA_Oligo...
        ] = Beard_NC_simulatePopulation(2, Par_vary, percentage_cells)


    
                                [Oxygen_5(:,:),  delPsi_basal_5, ATP_m_basal_5, NADH_m_basal_5, ATP_c_basal_5, H2O2_c_basal_5,...
        delPsi_FCCP, ATP_m_FCCP, NADH_m_FCCP, ATP_c_FCCP,...
        delPsi_FCCP_Rot, ATP_m_FCCP_Rot, NADH_m_FCCP_Rot, ATP_c_FCCP_Rot,...
        delPsi_FC_FCCP, delPsi_FC_FCCP_Rot, ATP_m_FC_FCCP, ATP_m_FC_FCCP_Rot,...
        NADH_m_FC_FCCP, NADH_m_FC_FCCP_Rot...
        ] = Beard_NC_simulatePopulation(5, Par_vary, percentage_cells)